#!/bin/bash
set -e

# Set up Vundle.
vundle_path="vim/bundle/Vundle.vim"
if [ ! -d ${vundle_path} ]; then
    git clone git@github.com:VundleVim/Vundle.vim.git
fi

# Install Vim plugins.
vim +PluginInstall +qall

# Fetch dependencies.
git submodule update --init --recursive

# Set safe symbolic links.
link () {
    filename=$1
    dotfile=${HOME}/.dotfiles/${filename}
	rootfile=${HOME}/.${filename}
	if [ ! -L $rootfile ]; then
	    echo "Linking $rootfile to $dotfile..."
        ln -s $dotfile $rootfile
    fi
}

# Do not symlink some files.
ignore_list="install LICENSE README.md scripts"

for file in *; do
	# Check if the file or directory should be symlinked.
	if ! echo $ignore_list | grep -w $file > /dev/null; then
		link $file
	fi
done
