#!/bin/bash
set -e

# Get location of this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Set a backup dir for existing dotfiles.
BACKUP_DIR=${HOME}/.backup_dotfiles

# Symlink the following files.
SYMLINK_LIST="config editorconfig gitconfig gitignore_global vim vimrc Xresources zshrc"

# Create symbolic links.
mkdir -p ${BACKUP_DIR}
link () {
	filename=$1
   	dotfile=${DIR}/${filename}
	rootfile=${HOME}/.${filename}
	if [ -L $rootfile ]; then
		echo "Deleting existing symlink $rootfile..." 
		rm "$rootfile"
	fi
	if [ -e $rootfile ]; then
		echo "Moving $rootfile to ${BACKUP_DIR}..."
		mv "$rootfile" "$BACKUP_DIR"
    	fi
	echo "Linking $rootfile to $dotfile..."
        ln -s $dotfile $rootfile
}

contains() {
	[[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]]
}

for file in *; do
	if contains "$SYMLINK_LIST" "$file"; then
		link "$file"
	fi
done

VUNDLE_PATH="${DIR}/vim/bundle"
mkdir -p ${VUNDLE_PATH}
if [ ! -e ${VUNDLE_PATH}/Vundle.vim ]; then
	echo "Installing Vundle..."
   	cd ${VUNDLE_PATH} && git clone git@github.com:VundleVim/Vundle.vim.git
	echo "Vundle installed."
fi

echo "Installing vim plugins..."
vim +PluginInstall +qall
echo "Vim plugins installed."


