#!/bin/bash
set -e

# Set up Vundle.
vundle_path="vim/bundle/Vundle.vim"
if [ ! -d ${vundle_path} ]; then
    git clone git@github.com:VundleVim/Vundle.vim.git
else
    (cd ${vundle_path} && git pull)
fi

# Install Vim plugins.
vim +PluginInstall +qall

# Fetch dependencies.
git submodule update --init --recursive

# Set safe symbolic links.
backup_path="${HOME}/backup"
link () {
	dotfile=$1
	rootfile=${HOME}/.${dotfile}
	echo "Linking $rootfile to $dotfile..."
	if [ ! -L $rootfile ]; then
        ln -s $dotfile $rootfile
    fi
}

# Do not symlink some files.
ignore_list="install LICENSE README.md"

# Loop over all files and directories
# in the root folder.
if [ ! -d ${backup_path} ]; then
    mkdir ${backup_path}
fi

for file in *; do
	# Check if the file or directory should be symlinked.
	if ! echo $ignore_list | grep -w $file > /dev/null; then
		link $file
	fi
done
